export enum screens {
  ALL_CARDS = 'ALL_CARDS',
  ALL_CARDS_LIST = 'ALL_CARDS_LIST',
  CARD_DETAILS = 'CARD_DETAILS',
  ALL_SETS = 'ALL_SETS',
  ALL_SETS_LIST = 'ALL_SETS_LIST',
  SET_DETAILS = 'SERIE_DETAILS',
  ALL_SERIES = 'ALL_SERIES',
  ALL_SERIES_LIST = 'ALL_SERIES_LIST',
  SERIE_DETAILS = 'SERIE_DETAILS',
  TABS = 'TABS',
  DETAILS = 'DETAILS',
}
