export enum screens {
  ALL_CARDS = 'ALL_CARDS',
  CARD_DETAILS = 'CARD_DETAILS',
  ALL_SETS = 'ALL_SETS',
  SET_DETAILS = 'SERIE_DETAILS',
  ALL_SERIES = 'ALL_SERIES',
  SERIE_DETAILS = 'SERIE_DETAILS',
}
